### PR TITLE
node-wot: update description

### PR DESCRIPTION
**Pull request by egekorkan**
This updates the repository description which is currently just the name of the repo

### CODE REVIEW

**Comment by netomi** [comment]
change has been applied.

**Comment by relu91** [comment]
Thank you! Next time is it possible to wait for a review from at least two other project committers? Or can we define a sort of simple policy for this?

**Comment by netomi** [comment]
I am sorry, this seemed like a simple change that I approved right away. Normally, we add the project leads to PRs for approval of changes that are not that simple. I will look into ways how we can express that on an organization level that you would like to have 2 reviews from fellow committers.

**Comment by egekorkan** [comment]
I think one project lead would be also fine. Just that I am not even an official Eclipse Committer (the election is in progress) and this could mean that a random person with Eclipse account can change such public information. In any case, it was nice to see that this pipeline works really well and thank you @netomi for the quick interactions :)

**Pull request merged**
