### PR TITLE
chore(otterdog): simplify node-wot protection rules

### PR DESCRIPTION
**Pull request by relu91**
As discussed in #16 this PR simplify the protection rules and adds @danielpeintner and me as actors capable of bypassing the rule. I couldn't find a way to define a group (which is more future-proof), but for now, I would say it is sufficient.

### CODE REVIEW

**Comment by relu91** [comment]
Ah, I've just noticed that we have github teams in the organization, what should we do? create a iot-thingweb-node-wot-leads group? @egekorkan @danielpeintner @JKRhb

**Comment by netomi** [comment]
Creating a team and adding people to the team would be better instead of having individuals defined as bypass actors.

If you give me a good team name I can create it and add the members according to your needs. Then we can adjust this PR accordingly.

**Comment by danielpeintner** [comment]
> Creating a team and adding people to the team would be better instead of having individuals defined as bypass actors.
> 
> If you give me a good team name I can create it and add the members according to your needs. Then we can adjust this PR accordingly.

Personally I am more in favor of listing individuals. 
The list of bypass actors will be very short and different from thingweb project to project. Hence I think adding individuals names is easier to handle instead of coming up with "team names" for each project over an over again. Moreover, this team would solely exist for bypassing PRs.

What do others think?

**Review by danielpeintner — APPROVED** [review]

**Comment by netomi** [comment]
if you all agree we can then merge the PR as is.

**Comment by JKRhb** [comment]
> Ah, I've just noticed that we have github teams in the organization, what should we do? create a iot-thingweb-node-wot-leads group? @egekorkan @danielpeintner @JKRhb

I guess we could also go for something shorter, like `node-wot-leads`, right? (As we are now in our own organization?) However, I am also fine with the current approach :)

**Review by JKRhb — APPROVED** [review]

**Review by netomi — APPROVED** [review]

**Pull request merged**
